ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 20.0
    sensor_timeout: 0.2

    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.1

    print_diagnostics: true
    debug: false
    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Wheel odometry only provides forward velocity.
    odom0: /wheel/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # IMU provides relative yaw and yaw angular velocity.
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true